### ISSUE TITLE
 EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by sf-arte** [sf-arte/GitHubSearch2#2]
コンパイルは通ったが，検索結果が表示されない

**Comment by sf-arte** [comment]
IBOutlet, IBActionの設定ができていない

**Comment by sf-arte** [comment]
StoryboardのViewControllerのCustom Classが設定されていなかった．
IBOutlet, IBActionの問題は解決.

Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)で落ちる．

**Comment by sf-arte** [comment]
SearchViewController.swiftの99行目
guard let searchManager = SearchRepositoriesManager(github: appContext.github, query: searchText) else { return }

**Comment by nkgwj** [comment]
IUO(Implicitly Unwrapped Optional)型のappContextがnilなのに
appContext.githubにアクセスしようとして死んでる感じでしょうか。

https://github.com/hatena/swift-Sample-GitHubSearch/blob/master/GitHubSearch/AppDelegate.swift#L36

はてなのサンプルでは、AppDelegateでApplicationContextのインスタンスをセットしているみたいです。

**Comment by sf-arte** [comment]
確認したところ，ご指摘の通りappContextの設定を忘れていました．
サンプルのようにAppDelegate.swiftで設定するように修正したところ，EXC_BAD_INSTRUCTIONは解決しました.
ありがとうございました.
