### ISSUE TITLE
warning: 'get(_:parameters:success:failure:)' is deprecated

### ISSUE THREAD

**Issue by sf-arte** [sf-arte/GitHubSearch2#3]
GitHub.swift:116:32: 'get(_:parameters:success:failure:)' is deprecated

代わりのメソッドがわからない．

**Comment by nkgwj** [comment]
'get(_:parameters:progress:success:failure:)' は如何でしょう。

**Comment by sf-arte** [comment]
解決しました．ありがとうございます．

**Comment by nkgwj** [comment]
https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide 

ご参考まで。

**Comment by nkgwj** [comment]
参考までに

# 調査手順

## 当該部分がdeprecatedとなっていることを確認

https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFHTTPSessionManager.h#L145

## 関連するコミットを探す(GithubのBlameやHistoryなどを使えばよい）

https://github.com/AFNetworking/AFNetworking/commits/master/AFNetworking/AFHTTPSessionManager.h

```
kcharwood Added a `deprecated` flag to older methods in the API

kcharwood New Progress Reporting API


These changes expose a simpler, block based progress reporting API, while maintaining the ability for more advanced features using KVO on NSProgress.

```

同じ日に新しいAPIが追加され、古いAPIがdeprecatedされていることを確認

## 確認として、得たヒントとなるキーワード(progress) を参考にAPIの変更に関連するドキュメントを探す

https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide を発見

**Comment by sf-arte** [comment]
なるほど，GitHubから探せば良いのですね．
勉強になりました，ありがとうございます．
